version: "3.8"


services:
    club_django_wsgi:
        container_name: club_django_wsgi
        env_file:
            - .env
        build:
            context: .
            dockerfile: ./Docker/Django/Dockerfile
            target: wsgi
        ports: 
            - "8001"
        volumes:
            - ./app:/app
            - ./Docker:/Docker
        depends_on:
            - club_database_container
        networks:
            - club-network
        command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py create_admin && python manage.py runserver 0.0.0.0:8000"

    club_django_asgi:
        container_name: club_django_asgi
        env_file:
            - .env
        build:
            context: .
            dockerfile: ./Docker/Django/Dockerfile
            target: asgi
        command: ["gunicorn", "main.asgi:application", "-k", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8001", "--reload"]
        volumes:
            - ./app:/app
            - ./Docker:/Docker
        ports: 
           - "8002"
        networks:
            - club-network

    club_database_container:
        container_name: club_database_container
        env_file:
            - .env
        build:
            context: .
            dockerfile: ./Docker/Database/Dockerfile
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - 5433:${POSTGRES_PORT}
        networks:
          - club-network        

    club_nginx:
        container_name: club_nginx
        build:
            context: .
            dockerfile: ./Docker/Nginx/Dockerfile
        ports:
          - "80:80"
          - "443:443"
        depends_on:
            - club_django_wsgi
            - club_django_asgi
        volumes:
            - .:/app
            - ./xxx/cert1.pem:/etc/nginx/certs/cert.pem:ro
            - ./xxx/privkey1.pem:/etc/nginx/certs/key.pem:ro
            - ./app/static:/static
        networks:
          - club-network

    ttc_redis:
        container_name: ttc_redis
        image: redis:7.0-alpine
        ports:
            - "6381:6379"
        restart: always
        depends_on:
            - club_django_wsgi
            - club_django_asgi
        networks:
            - club-network


networks:
    club-network:
