version: "3.8"


services:
    club_django_wsgi:
        container_name: club_django_wsgi
        env_file:
            - .env
        build:
            context: .
            dockerfile: ./Docker/Django/Dockerfile
            target: wsgi
        ports: 
            - "8000"
        volumes:
            - ./app:/app
        depends_on:
            - club_database_container
        networks:
            - club-network
        command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py create_admin && python manage.py runserver 0.0.0.0:8000"

    club_django_asgi:
        container_name: club_django_asgi
        env_file:
            - .env
        build:
            context: .
            dockerfile: ./Docker/Django/Dockerfile
            target: asgi
        command: ["gunicorn", "main.asgi:application", "-k", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8001", "--reload"]
        volumes:
            - ./app:/app
            - ./Docker:/Docker
        ports: 
           - "8001"
        networks:
            - club-network

    club_telegram_bot:
        container_name: club_telegram_bot
        env_file:
            - .env
        build:
            context: .
            dockerfile: ./Docker/Django/Dockerfile
        command: sh -c "python manage.py bot_setup"
        depends_on:
            - club_django_wsgi
            - club_django_asgi
        volumes:
            - ./app:/app
        networks:
            - club-network

    club_database_container:
        container_name: club_database_container
        env_file:
            - .env
        build:
            context: .
            dockerfile: ./Docker/Database/Dockerfile
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        networks:
          - club-network        

    club_nginx:
        container_name: club_nginx
        build:
            context: .
            dockerfile: ./Docker/Nginx/Dockerfile
        ports:
          - "80:80"
        depends_on:
            - club_django_wsgi
            - club_django_asgi
        volumes:
            - .:/app
        networks:
          - club-network

    ttc_redis:
        container_name: ttc_redis
        image: redis:7.0-alpine
        ports:
            - "6381:6379"
        restart: always
        depends_on:
            - club_django_wsgi
            - club_django_asgi
        networks:
            - club-network


networks:
    club-network:
