# Generated by Django 5.0.4 on 2024-05-06 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_admin',
            field=models.ForeignKey(help_text='Tournament Admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_admin', to='user.tournamentadmin', verbose_name='Tournament Admin'),
        ),
    ]
