# Generated by Django 5.0.4 on 2024-07-14 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tournament", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="tournament_admin",
            field=models.ForeignKey(
                help_text="Tournament Admin",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournament_admin",
                to="user.tournamentadmin",
                verbose_name="Tournament Admin",
            ),
        ),
        migrations.AddField(
            model_name="tournamentplayers",
            name="player",
            field=models.ForeignKey(
                help_text="Участник турнира",
                on_delete=django.db.models.deletion.CASCADE,
                to="user.player",
                verbose_name="Участник турнира",
            ),
        ),
        migrations.AddField(
            model_name="tournamentplayers",
            name="tournament",
            field=models.ForeignKey(
                help_text="Проводимый клубом туринр.",
                on_delete=django.db.models.deletion.CASCADE,
                to="tournament.tournament",
                verbose_name="Проводимый клубом туринр.",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tournamentplayers",
            unique_together={("tournament", "player")},
        ),
    ]
