# Generated by Django 5.0.4 on 2024-07-16 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0002_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_player_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="How much sets first player wins",
                        null=True,
                        verbose_name="How much sets first player wins",
                    ),
                ),
                (
                    "second_player_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="How much sets second player wins",
                        null=True,
                        verbose_name="How much sets second player wins",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "CREATED"), (1, "STARTED"), (2, "FINISHED")],
                        help_text="Game's status: created, started or finished",
                        null=True,
                        verbose_name="Game's status: created, started or finished",
                    ),
                ),
                (
                    "first_player",
                    models.ForeignKey(
                        help_text="One of two players of game",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games_first_player",
                        to="user.player",
                        verbose_name="One of two players of game",
                    ),
                ),
                (
                    "second_player",
                    models.ForeignKey(
                        help_text="One of two players of game",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games_second_player",
                        to="user.player",
                        verbose_name="One of two players of game",
                    ),
                ),
            ],
            options={
                "verbose_name": "Game",
                "verbose_name_plural": "Games",
                "db_table": "games",
            },
        ),
    ]
