# Generated by Django 5.0.4 on 2024-07-16 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0003_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="tournament",
            field=models.ForeignKey(
                help_text="Tournament",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games_of_tournament",
                to="tournament.tournament",
                verbose_name="Tournament",
            ),
        ),
    ]
