# Generated by Django 5.0.4 on 2024-07-16 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0004_game_tournament"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="order",
            field=models.PositiveSmallIntegerField(
                help_text="Order of game inside group stage",
                null=True,
                verbose_name="Order of game inside group stage",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="first_player",
            field=models.ForeignKey(
                help_text="One of two players of game",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games_first_player",
                to="tournament.tournamentplayers",
                verbose_name="One of two players of game",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="second_player",
            field=models.ForeignKey(
                help_text="One of two players of game",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games_second_player",
                to="tournament.tournamentplayers",
                verbose_name="One of two players of game",
            ),
        ),
    ]
