# Generated by Django 5.0.4 on 2024-08-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0005_game_order_alter_game_first_player_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "CREATED"), (1, "STARTED"), (2, "FINISHED")],
                default=0,
                help_text="Game's status: created, started or finished",
                null=True,
                verbose_name="Game's status: created, started or finished",
            ),
        ),
    ]
