# Generated by Django 5.0.4 on 2024-11-11 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_club_features'),
        ('tournament', '0006_alter_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='club',
            field=models.ForeignKey(help_text='Club where tournament run', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_tournaments', to='club.club', verbose_name='Club where tournament run'),
        ),
    ]
