# Generated by Django 5.0.4 on 2024-11-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0007_alter_tournament_club"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="group_number",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
