# Generated by Django 5.0.4 on 2024-11-23 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_game_group_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnockoutGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_player_score', models.PositiveSmallIntegerField(default=0, help_text='How much sets first player wins', null=True, verbose_name='How much sets first player wins')),
                ('second_player_score', models.PositiveSmallIntegerField(default=0, help_text='How much sets second player wins', null=True, verbose_name='How much sets second player wins')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'CREATED'), (1, 'STARTED'), (2, 'FINISHED')], default=0, help_text="Game's status: created, started or finished", null=True, verbose_name="Game's status: created, started or finished")),
                ('order', models.PositiveSmallIntegerField(help_text='Order of game inside group stage', null=True, verbose_name='Order of game inside group stage')),
                ('first_player', models.ForeignKey(help_text='One of two players of game', on_delete=django.db.models.deletion.CASCADE, related_name='knockout_games_first_player', to='tournament.tournamentplayers', verbose_name='One of two players of game')),
                ('second_player', models.ForeignKey(help_text='One of two players of game', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knockout_games_second_player', to='tournament.tournamentplayers', verbose_name='One of two players of game')),
                ('tournament', models.ForeignKey(help_text='Tournament', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knockout_games_of_tournament', to='tournament.tournament', verbose_name='Tournament')),
            ],
            options={
                'verbose_name': 'Knockout Game',
                'verbose_name_plural': 'Knockout Games',
                'db_table': 'knockout_games',
            },
        ),
    ]
