# Generated by Django 5.0.4 on 2024-11-29 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_alter_tournamentplayers_tournament'),
        ('user', '0004_alter_user_geo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='group_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of groups in tournament', null=True, verbose_name='Number of groups in tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='group_players_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of players in one group', null=True, verbose_name='Number of players in one group'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_admin',
            field=models.ForeignKey(blank=True, help_text='Tournament Admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_admin', to='user.tournamentadmin', verbose_name='Tournament Admin'),
        ),
    ]
