# Generated by Django 5.0.4 on 2024-11-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_alter_tournament_group_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='group_qualifiers_number',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of players who successfully left the group', null=True, verbose_name='Number of players who successfully left the group'),
        ),
    ]
