# Generated by Django 5.0.4 on 2024-11-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_alter_tournament_group_qualifiers_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.IntegerField(choices=[(0, 'CREATED'), (1, 'APPROVED'), (2, 'CONFIGURED'), (3, 'TOURNAMENT_STARTED'), (4, 'RUNING_NOW'), (5, 'FINISHED')], default=0, help_text='Created, started, running or finished. ', max_length=16, null=True, verbose_name='Tournament Status'),
        ),
    ]
