# Generated by Django 5.0.4 on 2024-11-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0013_alter_tournament_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentplayers',
            name='tournament_group',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Группа игрока на турнире', null=True, verbose_name='Группа игрока на турнире'),
        ),
    ]
