# Generated by Django 5.0.4 on 2024-11-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_alter_tournamentplayers_tournament_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.IntegerField(choices=[(0, 'CREATED'), (1, 'APPROVED'), (2, 'CONFIGURED'), (3, 'TOURNAMENT_STARTED'), (4, 'RUNING_NOW'), (5, 'FINISHED')], default=0, help_text='Created, started, running or finished. ', null=True, verbose_name='Tournament Status'),
        ),
    ]
