# Generated by Django 5.0.4 on 2024-11-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_alter_tournament_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentplayers',
            name='stage',
            field=models.IntegerField(choices=[(0, 'START'), (1, 'GROUP_STAGE')], help_text='Этап, на котором находится игрок в рамках турнира. ', null=True, verbose_name='Этап, на котором находится игрок в рамках турнира. '),
        ),
    ]
