# Generated by Django 5.0.4 on 2024-11-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0016_alter_tournamentplayers_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knockoutgame',
            name='order',
        ),
        migrations.AddField(
            model_name='knockoutgame',
            name='horizontal_order',
            field=models.PositiveSmallIntegerField(help_text='Это по горизонтали. Нет времени объяснять. ', null=True, verbose_name='Order of game inside group stage'),
        ),
        migrations.AddField(
            model_name='knockoutgame',
            name='vertical_order',
            field=models.PositiveSmallIntegerField(help_text='Это в какои верткали находится', null=True, verbose_name='Order of game inside group stage'),
        ),
    ]
