# Generated by Django 5.0.4 on 2024-12-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0017_remove_knockoutgame_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knockoutgame',
            name='is_game_for_first_place',
            field=models.BooleanField(default=False, help_text='True, если за игра зе первое место. По умолчанию ставится False', verbose_name='Игра за первое место или нет'),
        ),
        migrations.AddField(
            model_name='knockoutgame',
            name='is_game_for_third_place',
            field=models.BooleanField(default=False, help_text='True, если за игра зе третье место. По умолчанию ставится False.', verbose_name='Игра за третье место или нет.'),
        ),
    ]
