# Generated by Django 5.0.4 on 2024-06-16 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="playing_nahd",
            new_name="playing_hand",
        ),
    ]
