# Generated by Django 5.0.4 on 2024-05-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(help_text="User's birth date", null=True, verbose_name="User's birth date"),
        ),
    ]
