# Generated by Django 5.0.4 on 2024-09-03 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerRatingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateField(
                        blank=True,
                        help_text="Created date, time",
                        null=True,
                        verbose_name="Date,",
                    ),
                ),
                ("actual_rating", models.PositiveIntegerField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.player"
                    ),
                ),
            ],
            options={
                "verbose_name": "Player's rating history",
                "verbose_name_plural": "Player's rating history",
                "db_table": "player_rating_history",
            },
        ),
    ]
