# Generated by Django 5.0.4 on 2024-11-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_geo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='geo',
            field=models.CharField(choices=[(1, 'Dubai'), (2, 'Abu Dhabi'), (3, 'Sharjah'), (4, 'Other Emirate')], help_text='User can choose 1 from 4 variants', max_length=128, null=True, verbose_name="User's geo"),
        ),
    ]
