# Generated by Django 5.0.4 on 2024-11-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_geo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='playing_hand',
            field=models.IntegerField(choices=[(0, 'RIGHT_HAND'), (1, 'LEFT_HAND'), (2, 'BOTH')], help_text='By which hand player prefer to play, or both', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='geo',
            field=models.IntegerField(choices=[(1, 'Dubai'), (2, 'Abu Dhabi'), (3, 'Sharjah'), (4, 'Other Emirate')], help_text='User can choose 1 from 4 variants', max_length=128, null=True, verbose_name="User's geo"),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(0, 'MALE'), (1, 'FEMALE')], help_text="Choise of player's sex", max_length=16),
        ),
    ]
