# Generated by Django 5.0.4 on 2024-11-29 20:02

import main.utils
import user.models.player
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_player_blade_alter_player_playing_hand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, help_text='User Photo', null=True, upload_to=user.models.player.define_user_photo_path, validators=[main.utils.image_file_extension_validator], verbose_name='User Photo'),
        ),
    ]
