# Generated by Django 5.0.4 on 2024-12-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_player_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                blank=True,
                help_text="User's birth date",
                null=True,
                verbose_name="User's birth date",
            ),
        ),
    ]
