# Generated by Django 5.0.4 on 2024-12-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_geo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(0, 'MALE'), (1, 'FEMALE')], help_text="Choise of player's sex"),
        ),
    ]
