# Generated by Django 5.0.4 on 2024-05-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official name of club', max_length=128, null=True, verbose_name='Club Name')),
                ('state', models.CharField(help_text='State where club is placed', max_length=64, null=True, verbose_name='State')),
                ('city', models.CharField(help_text='City where club is placed', max_length=64, null=True, verbose_name='City')),
                ('address', models.CharField(help_text='Street, where club is placed', max_length=256, null=True, verbose_name='Club Address')),
                ('about', models.TextField(help_text='Additional info about club', null=True, verbose_name='About Club')),
                ('link', models.URLField(help_text='Link to club site, any info in Ethernet', null=True, verbose_name='Club Site')),
            ],
        ),
    ]
