# Generated by Django 5.0.4 on 2024-05-13 15:03

import club.models.club
import club.models.club_photoes
import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Created date, time', null=True, verbose_name='Created date, time')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date, time', null=True, verbose_name='Created date, time')),
                ('is_active', models.BooleanField(default=True, help_text='Project use this field instead of full removing object from database. Just deactivate ', verbose_name='Object is active of not')),
                ('name', models.CharField(help_text='Official name of club', max_length=128, null=True, verbose_name='Club Name')),
                ('logo', models.ImageField(help_text='Club logo', null=True, upload_to=club.models.club.define_logo_path, validators=[main.utils.image_file_extension_validator], verbose_name='Club Logo')),
                ('state', models.CharField(help_text='State where club is placed', max_length=64, null=True, verbose_name='State')),
                ('city', models.CharField(help_text='City where club is placed', max_length=64, null=True, verbose_name='City')),
                ('address', models.CharField(help_text='Street, where club is placed', max_length=256, null=True, verbose_name='Club Address')),
                ('phone_number', models.CharField(help_text='Phone number of club', null=True, verbose_name='Phone number')),
                ('opening_hours', models.JSONField(help_text='Days and hours when club is working', null=True, verbose_name='Opening hours')),
                ('about', models.TextField(help_text='Additional info about club', null=True, verbose_name='About Club')),
                ('social_link', models.URLField(help_text='Link to club social network page', null=True, verbose_name='Club Social Network page')),
                ('link', models.URLField(help_text='Link to club site, any info in Ethernet', null=True, verbose_name='Club Site')),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'db_table': 'clubs',
            },
        ),
        migrations.CreateModel(
            name='ClubPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Created date, time', null=True, verbose_name='Created date, time')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Update date, time', null=True, verbose_name='Created date, time')),
                ('photo', models.ImageField(help_text="URL on which project store photo's URL on server", null=True, upload_to=club.models.club_photoes.define_club_photo_path, validators=[main.utils.image_file_extension_validator], verbose_name='Url of club Photo')),
            ],
            options={
                'verbose_name': 'Club Photo',
                'verbose_name_plural': 'Club Photoes',
                'db_table': 'club_photoes',
            },
        ),
    ]
