# Generated by Django 5.0.4 on 2024-11-06 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubphoto",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="club_photoes",
                to="club.club",
            ),
        ),
    ]
