# Generated by Django 5.0.4 on 2024-11-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_clubphoto_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='features',
            field=models.JSONField(help_text='Данное поле следует заполнять строго в таком порядке: {"1": "первая фича", "2": "вторая фича"}', null=True, verbose_name='Club Features'),
        ),
    ]
