# Generated by Django 5.0.4 on 2024-11-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_club_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='opening_hours',
            field=models.JSONField(help_text='{"MONDAY": {"START": "10:30", "FINISH": "21:00"}}', null=True, verbose_name='Opening hours'),
        ),
    ]
